kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "travelsite-mysql-db" 
spec:
  runPolicy: "Serial"
  source:
    git:
      uri: https://github.com/Quarkus-Travel-Site-Martins96/Database-Travel-Scripts
    contextDir: .
    configMaps:
    - configMap:
        name: mysql-db-script.sql
  strategy:
    type: Docker                      
    dockerStrategy:
      dockerfilePath: "."
  output:
    to:
      kind: "ImageStreamTag"
      name: "travelsite-mysql-db:latest"